### ISSUE TITLE
question about the edge type

### ISSUE THREAD

**Issue by shi27feng** [wheatman/Packed-Compressed-Sparse-Row#1]
Hi,
I'm curious what exactly the "value" stores in the below data structure?

```C++
typedef struct _edge {
  uint32_t dest; // destination of this edge in the graph, MAX_INT if this is a
                 // sentinel
  uint32_t
      value; // edge value of zero means it a null since we don't store 0 edges
} edge_t;
```

Does it provide the weight of the edge or any other information?
Thank you very much in advance!

**Comment by wheatman** [comment]
yes, that is for storing the weight of an edge
